---
- name: Append SSL folder for Postgres user
  ansible.builtin.user:
    name: "{{ postgresql_user }}"
    groups:
      - ssl-cert
    append: true

- name: Configuring memory overcommit - Sysctl configurations
  loop: "{{ postgresql_sysctl_params }}"
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true

- name: Configure secure socket directory
  ansible.builtin.file:
    path: "{{ postgresql_unix_socket_folder }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0700"
    state: directory
  notify: Reload daemon

- name: Create PostgreSQL log directory
  ansible.builtin.file:
    path: "{{ postgresql_log_folder }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0750"
    state: directory

- name: Sends custom server configuration
  ansible.builtin.template:
    src: "{{ postgresql_config_template_path }}"
    dest: "{{ postgresql_conf_path }}"
    mode: "0660"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"

- name: Sends custom pg_hba configuration
  ansible.builtin.template:
    src: "{{ postgresql_hba_template_path }}"
    dest: "{{ postgresql_hba_path }}"
    mode: "0660"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
