---
- name: Gather facts
  ansible.builtin.setup:

- name: PostgreSQL installation
  ansible.builtin.include_tasks: install.yml

- name: PostgreSQL configuration
  ansible.builtin.include_tasks: configure.yml

- name: User creation if enabled
  when: postgresql_user_enable
  ansible.builtin.include_tasks: user.yml

- name: Database creation if enabled
  when: postgresql_database_enable
  ansible.builtin.include_tasks: database.yml
