---
- name: Gather facts
  ansible.builtin.setup:

- name: PostgreSQL installation
  ansible.builtin.include_tasks: install.yml

- name: PostgreSQL configuration
  ansible.builtin.include_tasks: configure.yml

- name: Creates SSL certificate
  when: postgresql_ssl_enable
  ansible.builtin.import_role:
    name: ssl
  vars:
    ssl_dns_enabled: "{{ postgresql_ssl_dns_enabled }}"
    ssl_provider: "{{ postgresql_ssl_provider }}"
    ssl_credentials: "{{ postgresql_ssl_credentials }}"
    ssl_generate: true
    ssl_generate_domain: "{{ postgresql_ssl_domain }}"
    ssl_generate_output_path: "{{ postgresql_ssl_output_path }}"
    ssl_generate_csr_path: "{{ postgresql_ssl_csr_path }}"
    ssl_generate_csr_owner: "{{ postgresql_ssl_csr_owner }}"
    ssl_generate_csr_group: "{{ postgresql_ssl_csr_group }}"
    ssl_generate_privatekey_path: "{{ postgresql_ssl_privatekey_path }}"
    ssl_generate_email: "{{ postgresql_ssl_email }}"
    ssl_generate_owner: "{{ postgresql_user }}"
    ssl_generate_group: "{{ postgresql_group }}"
  notify: Restart PostgreSQL
