---
- name: Installs required packages
  ansible.builtin.apt:
    name:
      - wget
      - gnupg
      - apt-transport-https
      - ca-certificates
    update_cache: true

- name: Downloads GPG key
  ansible.builtin.get_url:
    url: "{{ lynis_key_host }}"
    dest: "{{ lynis_temp_path }}"
    mode: "0644"

- name: Verify Lynis GPG key fingerprint
  register: lynis_gpg_output
  changed_when: false
  failed_when: lynis_hashsum not in lynis_gpg_output.stdout
  ansible.builtin.command:
    cmd: "gpg --dry-run --quiet --no-keyring --import --import-options import-show {{ lynis_temp_path }}"

- name: Dearmor Lynis GPG key
  ansible.builtin.command:
    cmd: "gpg --dearmor -o {{ lynis_keyring_path }} {{ lynis_temp_path }}"
    creates: "{{ lynis_keyring_path }}"

- name: Remove temporary key file
  ansible.builtin.file:
    path: "{{ lynis_temp_path }}"
    state: absent

- name: Add official repository to apt sources
  ansible.builtin.apt_repository:
    repo: "{{ lynis_apt_config }}"
    state: present
    filename: lynis
    update_cache: true

- name: Install Lynis
  ansible.builtin.apt:
    name: lynis
    state: present
