---
- name: Downloads required packages
  ansible.builtin.apt:
    name: "{{ openldap_required_packages }}"
    state: present
    update_cache: true

- name: Downloads software
  ansible.builtin.unarchive:
    src: "{{ openldap_host }}"
    dest: "{{ openldap_temp_folder }}"
    remote_src: true
