---
grype_package_name: grype
grype_group: grype
grype_user: grype
grype_time:
  weekday: "0"
  hour: "3"
  minute: "0"

# Config paths - Should not be changed
grype_host: https://get.anchore.io/grype
grype_cosign_url: https://github.com/sigstore/cosign/releases/download/v3.0.5/cosign-linux-amd64
grype_cosign_binary_path: /usr/local/sbin/cosign-linux-amd64
grype_binary_path: /usr/local/sbin/grype
grype_binary_folder: /usr/local/sbin
grype_config_folder: /etc/grype
grype_log_folder: /var/log/grype
grype_custom_config_path: /etc/grype/config.yaml
grype_log_path: /var/log/grype/audit.log
grype_job_title: "Grype audit - EasySec"
grype_job: "{{ grype_binary_path }} / 2>&1"
