---
- name: Installing OpenJDK
  ansible.builtin.apt:
    name:
      - "{{ keycloak_java_package }}"
    update_cache: true

- name: Downloads software
  ansible.builtin.get_url:
    url: "{{ keycloak_host }}"
    dest: "{{ keycloak_temp_path }}"
    mode: "0600"
