---
- name: Downloads cosign installation script
  ansible.builtin.get_url:
    url: "{{ grant_cosign_url }}"
    dest: "{{ grant_cosign_binary_path }}"
    mode: "0555"

- name: Downloads installation script
  ansible.builtin.get_url:
    url: "{{ grant_host }}"
    dest: /tmp/grant_install.sh
    mode: "0700"

- name: Install Grant
  ansible.builtin.command:
    cmd: /tmp/grant_install.sh -b {{ grant_binary_folder }} -v
    creates: "{{ grant_binary_path }}"

- name: Installation script removal
  ansible.builtin.file:
    path: /tmp/grant_install.sh
    state: absent
