---
all:
  hosts:
    vagrant-manager-1:
      ansible_host: 192.168.56.2
      ansible_port: 22

    vagrant-kali-1:
      ansible_host: 192.168.56.3
      ansible_port: 22

    vagrant-ubuntu-1:
      ansible_host: 192.168.56.4
      ansible_port: 22

    vagrant-keycloak-1:
      ansible_host: 192.168.56.5
      ansible_port: 22
