---
# KRNL-5820
- name: Disabling Core dumps
  notify: Daemon refresh
  block:
    - name: Applies configurations for coredumps policies
      loop: "{{ hardening_coredumps_policies.blocks }}"
      ansible.builtin.blockinfile:
        create: true
        mode: "0644"
        owner: "{{ hardening_user }}"
        group: "{{ hardening_group }}"
        path: "{{ item.path }}"
        marker: "{{ hardening_header }}"
        block: "{{ item.config }}"
        insertafter: "{{ item.position }}"
        backup: true

    - name: Applies configurations for coredumps policies
      loop: "{{ hardening_coredumps_policies.lines }}"
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regex }}"
        line: "{{ item.data }}"
        state: present
        backup: true
