---
# AUTH-9230, AUTH-9286, AUTH-9328, AUTH-9282
- name: Enforcing password strength and account password locking
  when: hardening_passwords
  block:
    - name: Applies configurations for password policies
      loop: "{{ hardening_password_policies.lines }}"
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regex }}"
        line: "{{ item.data }}"
        state: present
        backup: true

    - name: Locks root account password
      ansible.builtin.user:
        name: root
        state: present
        password_lock: true
