---
# PKGS-7370, PKGS-7394
- name: Downloads and configures required software
  block:
    - name: Downloads packages
      ansible.builtin.apt:
        name:
          - debsums
          - apt-show-versions
        update_cache: true
        state: present
