---
# NETW-3200
- name: Restricting network protocols
  block:
    - name: Applies configurations for protocol policies
      loop: "{{ hardening_protocol_policies.blocks }}"
      ansible.builtin.blockinfile:
        create: true
        mode: "0644"
        owner: "{{ hardening_user }}"
        group: "{{ hardening_group }}"
        path: "{{ item.path }}"
        marker: "{{ hardening_header }}"
        block: "{{ item.config }}"
        insertafter: "{{ item.position }}"
        backup: true

    - name: Disables dccp protocol
      community.general.modprobe:
        name: dccp
        state: absent

    - name: Disables sctp protocol
      community.general.modprobe:
        name: sctp
        state: absent

    - name: Disables rds protocol
      community.general.modprobe:
        name: rds
        state: absent

    - name: Disables tipc protocol
      community.general.modprobe:
        name: tipc
        state: absent
