---
keycloak_hostname: "keycloak.x"
keycloak_user: keycloak
keycloak_group: keycloak
keycloak_enable_database: true

# Config envs - Should not be changed unless knowing what they do
## Config
keycloak_package_name: keycloak
keycloak_port: 8443
keycloak_java_package: openjdk-21-jdk
keycloak_host: https://github.com/keycloak/keycloak/releases/download/26.5.6/keycloak-26.5.6.tar.gz
keycloak_path: /opt/keycloak

## Folder
keycloak_config_folder: /etc/keycloak
keycloak_log_folder: /var/log/keycloak
keycloak_source_folder: /opt/keycloak

## Files
keycloak_config_path: "{{ keycloak_config_folder }}/keycloak.conf"
keycloak_unit_path: /etc/systemd/system/keycloak.service
keycloak_temp_path: /tmp/keycloak.tar.gz
keycloak_config_template_path: templates/keycloak.conf.j2
keycloak_unit_template_path: templates/service.conf.j2
keycloak_password_output_path: "{{ playbook_dir }}/../generated/keycloak_admin.txt"
keycloak_ssl:
  cert_path: /etc/ssl/certs/keycloak.pem
  key_path: /etc/ssl/private/keycloak.key
