---
- name: Downloads cosign installation script
  ansible.builtin.get_url:
    url: "{{ grype_cosign_url }}"
    dest: "{{ grype_cosign_binary_path }}"
    mode: "0555"

- name: Downloads installation script
  ansible.builtin.get_url:
    url: "{{ grype_host }}"
    dest: /tmp/grype_install.sh
    mode: "0700"

- name: Install Grype
  ansible.builtin.command:
    cmd: /tmp/grype_install.sh -b {{ grype_binary_folder }} -v
    creates: "{{ grype_binary_path }}"

- name: Installation script removal
  ansible.builtin.file:
    path: /tmp/grype_install.sh
    state: absent
