---
- name: Downloads cosign installation script
  ansible.builtin.get_url:
    url: "{{ syft_cosign_url }}"
    dest: "{{ syft_cosign_binary_path }}"
    mode: "0555"

- name: Downloads installation script
  ansible.builtin.get_url:
    url: "{{ syft_host }}"
    dest: /tmp/syft_install.sh
    mode: "0700"

- name: Install Syft
  ansible.builtin.command:
    cmd: /tmp/syft_install.sh -b {{ syft_binary_folder }} -v
    creates: "{{ syft_binary_path }}"

- name: Installation script removal
  ansible.builtin.file:
    path: /tmp/syft_install.sh
    state: absent
