---
- name: Downloads installation script
  ansible.builtin.get_url:
    url: "{{ syft_host }}"
    dest: "{{ syft_temp_path }}"
    mode: "0700"

- name: Install Syft
  ansible.builtin.command:
    cmd: "{{ syft_temp_path }} -b {{ syft_binary_folder }} -v"
    creates: "{{ syft_binary_path }}"

- name: Installation script removal
  ansible.builtin.file:
    path: "{{ syft_temp_path }}"
    state: absent
