---
- name: Generate certificate with certbot
  when: ssl_provider != "selfsigned" and ssl_generate
  block:
    - name: Generate certificate
      ansible.builtin.shell: |
        certbot certonly \
          --email {{ ssl_email }} \
          -d {{ ssl_domain }} \
          --non-interactive \
          --agree-tos \
          {% if ssl_dns_enabled %}
          --dns-{{ ssl_provider }} \
          --dns-{{ ssl_provider }}-credentials {{ ssl_credentials_folder }}/{{ ssl_provider }}.ini
          {% else %}
          --standalone
          {% endif %}
      changed_when: true

    - name: Deploy certificate and key
      loop:
        - { src: fullchain.pem, dest: "{{ ssl_cert_path }}", when: "{{ ssl_move_cert }}", mode: "0644" }
        - { src: privkey.key, dest: "{{ ssl_key_path }}", when: "{{ ssl_move_key }}", mode: "0600" }
      when: item.when
      ansible.builtin.copy:
        src: "{{ ssl_live_certs_folder }}/{{ ssl_domain }}/{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: true
        owner: "{{ ssl_user }}"
        group: "{{ ssl_group }}"
        mode: "{{ item.mode }}"

    - name: Deploy renewal script
      ansible.builtin.template:
        src: "{{ ssl_renewal_template_path }}"
        dest: "{{ ssl_live_certs_folder }}/{{ ssl_domain }}/renewal.sh"
        mode: "0750"

    - name: Configures cronjob to renew certificate
      ansible.builtin.cron:
        name: "{{ ssl_job_title }}"
        state: present
        hour: "0,12"
        user: "{{ ssl_user }}"
        minute: "15"
        job: "{{ ssl_job }}"

- name: Generate self-signed certificate
  when: ssl_provider == "selfsigned" and ssl_generate
  block:
    - name: Generate private key
      community.crypto.openssl_privatekey:
        path: "{{ ssl_key_path }}"
        owner: "{{ ssl_user }}"
        group: ssl-cert
        mode: "0640"

    - name: Generate certificate
      community.crypto.x509_certificate:
        path: "{{ ssl_cert_path }}"
        provider: selfsigned
        privatekey_path: "{{ ssl_key_path }}"
        owner: "{{ ssl_user }}"
        group: ssl-cert
        mode: "0644"
