---
- name: Generates a certificate using the provided credentials
  when: ssl_provider != "selfsigned"
  block:
    - name: Generates the certificate
      ansible.builtin.shell: |
        certbot certonly \
          --email {{ ssl_generate_email }} \
          -d {{ ssl_generate_domain }} \
          --non-interactive \
          --agree-tos {{ dns_args }}
      vars:
        dns_args: >-
          {% if ssl_dns_enabled %}
          --dns-{{ ssl_provider }}
          --dns-{{ ssl_provider }}-credentials {{ ssl_credentials_path }}/{{ ssl_provider }}.ini
          {% else %}
          --standalone
          {% endif %}
      changed_when: true

    - name: Sends the certificate to the specified path
      when: ssl_generate_output_path | length > 0
      ansible.builtin.copy:
        src: "{{ ssl_live_certs }}/{{ ssl_generate_domain }}/fullchain.pem"
        dest: "{{ ssl_generate_output_path }}"
        remote_src: true
        owner: "{{ ssl_generate_owner | default(ssl_user) }}"
        group: "{{ ssl_generate_group | default(ssl_group) }}"
        mode: "0600"

    - name: Sends the private key to the specified path
      when: ssl_generate_privatekey_path | length > 0
      ansible.builtin.copy:
        src: "{{ ssl_live_certs }}/{{ ssl_generate_domain }}/privkey.key"
        dest: "{{ ssl_generate_privatekey_path }}"
        remote_src: true
        owner: "{{ ssl_generate_owner | default(ssl_user) }}"
        group: "{{ ssl_generate_group | default(ssl_group) }}"
        mode: "0600"

    - name: Adds script for renewal
      ansible.builtin.template:
        src: templates/renewal.sh.j2
        dest: "{{ ssl_live_certs }}/{{ ssl_generate_domain }}/renewal.sh"
        mode: "0750"

    - name: Configures cronjob to renew certificate
      ansible.builtin.cron:
        name: "{{ ssl_job_title }}"
        state: present
        hour: "0,12"
        user: "{{ ssl_user }}"
        minute: "15"
        job: "{{ ssl_job }}"

- name: Generates a self-signed certficate
  when: ssl_provider == "selfsigned"
  block:
    - name: Generates the private key
      when: ssl_generate_privatekey_path | length > 0
      community.crypto.openssl_privatekey:
        path: "{{ ssl_generate_privatekey_path }}"
        owner: "{{ ssl_generate_owner | default(ssl_user) }}"
        group: "{{ ssl_generate_group | default(ssl_group) }}"
        mode: "0600"

    - name: Generates the CSR certificate
      when: ssl_generate_csr_path | length > 0
      community.crypto.openssl_csr:
        path: "{{ ssl_generate_csr_path }}"
        privatekey_path: "{{ ssl_generate_privatekey_path }}"
        common_name: "{{ ssl_generate_domain }}"
        subject_alt_name:
          - "DNS:{{ ssl_generate_domain }}"
          - "IP:{{ ansible_facts['default_ipv4']['address'] }}"
        owner: "{{ ssl_generate_csr_owner | default(ssl_user) }}"
        group: "{{ ssl_generate_csr_group | default(ssl_group) }}"
        mode: "0600"

    - name: Generates the selfsigned certificate
      when: ssl_generate_output_path | length > 0
      community.crypto.x509_certificate:
        path: "{{ ssl_generate_output_path }}"
        provider: selfsigned
        privatekey_path: "{{ ssl_generate_privatekey_path }}"
        owner: "{{ ssl_generate_owner | default(ssl_user) }}"
        group: "{{ ssl_generate_group | default(ssl_group) }}"
        mode: "0600"
