---
- name: Installs the default software
  ansible.builtin.apt:
    name:
      - certbot
    state: present
    update_cache: true

- name: Installs DigitalOcean DNS plugin
  when: ssl_dns and ssl_provider == "digitalocean"
  ansible.builtin.apt:
    name:
      - python3-certbot-dns-digitalocean
    state: present
    update_cache: true

- name: Installs OVH DNS plugin
  when: ssl_dns and ssl_provider == "ovh"
  ansible.builtin.apt:
    name:
      - python3-certbot-dns-ovh
    state: present
    update_cache: true

- name: Installs Cloudflare DNS plugin
  when: ssl_dns and ssl_provider == "cloudflare"
  ansible.builtin.apt:
    name:
      - python3-certbot-dns-cloudflare
    state: present
    update_cache: true
