---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Find old tor instance services
  ansible.builtin.set_fact:
    proxychains_tor_instances: "{{ ansible_facts.services.keys() | select('match', '^' ~ proxychains_service_start_name ~ '-.*\\.service$') | list }}"

- name: Stop and disable old tor instances
  become: true
  loop: "{{ proxychains_tor_instances }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false

- name: Deletes all previous logs
  ansible.builtin.file:
    path: "{{ proxychains_log_folder }}"
    state: absent
    force: true

- name: Deletes all previous data
  ansible.builtin.file:
    path: "{{ proxychains_lib_folder }}"
    state: absent
    force: true

- name: Deletes all previous configs
  ansible.builtin.file:
    path: "{{ proxychains_config_folder }}"
    state: absent
    force: true

- name: Deletes all previous units
  ansible.builtin.file:
    path: "{{ proxychains_service_unit_path }}"
    state: absent
    force: true

- name: Reloads daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Resets daemon (for failed units)
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: systemctl reset-failed
