---
- name: Tarball management
  block:
    - name: Sending to target
      ansible.builtin.copy:
        src: "{{ audit_tarball_path }}"
        dest: "{{ audit_tarball_dest_path }}"
        mode: "0775"

    - name: Decompression
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ audit_tarball_dest_path }}"
        dest: "{{ audit_remote_folder }}"

    - name: Removal
      ansible.builtin.file:
        path: "{{ audit_tarball_dest_path }}"
        state: absent

- name: Applying configuration templates
  block:
    - name: Sends Syft template
      ansible.builtin.template:
        src: "{{ audit_syft_template_path }}"
        dest: "{{ audit_remote_syft_config_path }}"
        mode: "0444"

    - name: Sends Grype template
      ansible.builtin.template:
        src: "{{ audit_grype_template_path }}"
        dest: "{{ audit_remote_grype_config_path }}"
        mode: "0444"

    - name: Sends Grant template
      ansible.builtin.template:
        src: "{{ audit_grant_template_path }}"
        dest: "{{ audit_remote_grant_config_path }}"
        mode: "0444"
