---
- name: Local setup
  ansible.builtin.include_tasks: local.yml

- name: Sending templates
  ansible.builtin.include_tasks: configure.yml

- name: Installation and execution
  ansible.builtin.include_tasks: execute.yml

- name: Extraction from target to local
  ansible.builtin.include_tasks: extract.yml
