---
- name: Generates a SSL certificate on test host (Vagrant)
  hosts: vagrant-jammy-1
  become: true
  roles:
    - ssl
  vars:
    ssl_provider: "selfsigned"
    ssl_generate: true
    ssl_generate_domain: "easysec.x"
    ssl_generate_output_path: "/opt/easysec.x.pem"
    ssl_generate_privatekey_path: "/opt/easysec.x.key"
    ssl_generate_email: "whoami@easysec.x"
